#Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: ammarkazi99/book-catalog:latest
        ports:
        - containerPort: 8000 
        env:
        - name: DATABASE_URL
          value: postgresql://sit722_part2_db_xbja_user:QFd4v5R3pKGFCk59BWep6gnrhENTkGlt@dpg-crie3itumphs73cj2k2g-a.oregon-postgres.render.com/sit722_part2_db_xbja  # external db url
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000
  selector:
    app: book-catalog
